version: "3"
volumes:
  tower-of-doors-grafana-volume-DB:
    driver: 'local'
  tower-of-doors-grafana-volume-etc:
    driver: 'local'
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/log:/var/log/mysql
      - ./mysql/db:/docker-entrypoint-initdb.d
    image: tower-of-doors-mysql
    container_name: tower-of-doors-mysql
    hostname: tod-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=KEqUG3wDAAZaU5hRHBC43DvUmTbFEdtPM49jqKRCA4RePBTPCVeeU4ZTjASdNnkv
    networks:
      - tower-of-doors-network
  grafana:
    build: ./grafana/
    volumes:
      - tower-of-doors-grafana-volume-DB:/var/lib/grafana
      - tower-of-doors-grafana-volume-etc:/etc/grafana
    image: tower-of-doors-grafana
    container_name: tower-of-doors-grafana
    hostname: tod-grafana
    networks:
      - tower-of-doors-network
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_INSTALL_PLUGINS: aceiot-svg-panel
      GF_RENDERING_SERVER_URL: http://tod-grafana-renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://tod-grafana:3000/
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: tower-of-doors-grafana-renderer
    hostname: tod-grafana-renderer
    networks:
      - tower-of-doors-network
  tod-logic:
    build: ./tod-logic/
    image: tower-of-doors-tod-logic
    container_name: tower-of-doors-tod-logic
    hostname: tod-logic
    networks:
      - tower-of-doors-network
    tty: true
networks:
  tower-of-doors-network:
    external: true