{
 "title": "Tower Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Tower Status Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status as \"Status\"\nFROM game_status\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  turn_player as \"Turn\"\nFROM game_status\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  status\nFROM game_status\nORDER BY `timestamp` DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIMEDIFF(now(), start_time)\nFROM game_status\nLEFT JOIN game ON game_status.game_id = game.id\nORDER BY `timestamp` DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Turn Player",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE WHEN turn_player > 0 THEN concat(turn_player, ' / ', player_num) WHEN turn_player=0 THEN concat('Interval / ', player_num) ELSE turn_player END AS value\nFROM game_status\nLEFT JOIN game ON game_status.game_id = game.id\nORDER BY `timestamp` DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Azimuth Timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  `timestamp` as `time`,\n  azimuth\nFROM azimuth_log\nWHERE $__timeFilter(`timestamp`)\nORDER BY `timestamp` ASC\n"
    }
   ]
  },
  {
   "title": "Azimuth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  azimuth\nFROM azimuth_log\nORDER BY `timestamp` DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Yawing to",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  aim_azimuth\nFROM yawing_schedule\nWHERE yawing_status = 'ON_YAWING'\nORDER BY schedule_start_time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Opened doors",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  id,\n  timestamp,\n  reason,\n  TIMESTAMPDIFF(SECOND, timestamp, now()) as passed\nFROM door_status\nWHERE status = 1\nORDER BY passed DESC\n"
    }
   ]
  }
 ]
}